name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test TextProcessLibTest/TextProcessLibTest.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage/test1
      
    - name: Test
      run: dotnet test TextProcessLibTest2/TextProcessLibTest2.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage/test2

    - name: Upload coverage report1
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report1
        path: coverage/test1/**/coverage.cobertura.xml
        
    - name: Upload coverage report2
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report2
        path: coverage/test2/**/coverage.cobertura.xml

  test-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report1
        path: coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'coverage/test1/**/coverage.cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      
  test2-coverage:
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
    - uses: actions/checkout@v3

    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report2
        path: coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'coverage/test2/**/coverage.cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
