name: Test and CoverageV3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '30 seconds'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test1
      run: dotnet test TextProcessLibTest\TextProcessLibTest.csproj --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/Test1Coverage/ -p:CoverletOutputFormat=opencover

    - name: Test2
      run: dotnet test TextProcessLibTest2\TextProcessLibTest2.csproj --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/Test2Coverage/ -p:CoverletOutputFormat=opencover

    - name: Merge coverage reports
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:D:\a\TextProcessLib\TextProcessLib\TextProcessLibTest\TestResults\Test1Coverage\coverage.opencover.xml;D:\a\TextProcessLib\TextProcessLib\TextProcessLibTest2\TestResults\Test2Coverage\coverage.opencover.xml" "-targetdir::D:\a\TextProcessLib\TextProcessLib\TextProcessLibTest\TestResults\Merged" -reporttypes:OpenCover
     
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: TextProcessLibTest/TestResults/Merged/coverage.opencover.xml

  test-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: coverage

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: 'coverage/**/coverage.opencover.xml'
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
